### PR TITLE
add user.getActiveProduct + tests

### PR DESCRIPTION
**Pull request by gka**
This PR adds the functionality to return the "active" product of a user. Like the [previous PHP implementation](https://github.com/datawrapper/datawrapper/blob/node-publishing/lib/core/build/classes/datawrapper/User.php#L324-L365] this checks both products through `UserProduct` and products through `TeamProduct`.

### CODE REVIEW

**Comment by gka** [comment]
Oh, one thing I didn't take from the original implementation is the ["fallback product"](https://github.com/datawrapper/datawrapper/blob/node-publishing/lib/core/build/classes/datawrapper/User.php#L359-L362). I guess we need the same here? Isn't it better to define the default product through the config?

**Comment by gka** [comment]
I guess it's useful to also look at the actual queries that are generated by calling `user.getActiveProducts` to review this PR. This is what is executed during the last test (user 5, who has no user product but is in two teams):

```sql
-- get user with id 5
SELECT `id`, `email`, `pwd`, `activate_token`,
    `reset_password_token`,  `role`, `deleted`, `language`, 
    `created_at`, `name`, `website`,  `sm_profile`,
    `oauth_signin`, `customer_id`, `created_at` AS `createdAt` 
    FROM `user` AS `user` WHERE `user`.`id` = 5;

-- get products for user with id 5
SELECT `product`.`id`, `product`.`name`, `product`.`deleted`,
    `product`.`priority`, `product`.`data`, 
    `product`.`created_at` AS `createdAt`,
    `user_product`.`user_id` AS `user_product.user_id`,
    `user_product`.`product_id` AS `user_product.product_id`,
    `user_product`.`created_by_admin` AS `user_product.created_by_admin`,
    `user_product`.`changes` AS `user_product.changes`,
    `user_product`.`expires` AS `user_product.expires`,
    `user_product`.`user_id` AS `user_product.userId`,
    `user_product`.`product_id` AS `user_product.productId`
    FROM `product` AS `product` 
    INNER JOIN `user_product` AS `user_product` 
        ON `product`.`id` = `user_product`.`product_id` 
            AND `user_product`.`user_id` = 5 
    ORDER BY `product`.`priority` DESC;

-- get teams for user with id 5
SELECT `team`.`id`, `team`.`name`, `team`.`settings`,
    `team`.`created_at` AS `createdAt`, `team`.`default_theme`,
    `user_team`.`organization_role` AS `user_team.team_role`,
    `user_team`.`invite_token` AS `user_team.invite_token`,
    `user_team`.`invited_at` AS `user_team.invited_at`,
    `user_team`.`user_id` AS `user_team.user_id`,
    `user_team`.`organization_id` AS `user_team.organization_id`,
    `user_team`.`invited_by` AS `user_team.invited_by` 
    FROM `organization` AS `team` 
    INNER JOIN `user_organization` AS `user_team` 
    ON `team`.`id` = `user_team`.`organization_id` 
        AND `user_team`.`user_id` = 5;

-- get products for team-2
SELECT `product`.`id`, `product`.`name`, `product`.`deleted`,
    `product`.`priority`, `product`.`data`,
    `product`.`created_at` AS `createdAt`,
    `team_product`.`created_by_admin` AS `team_product.created_by_admin`,
    `team_product`.`changes` AS `team_product.changes`,
    `team_product`.`expires` AS `team_product.expires`,
    `team_product`.`organization_id` AS `team_product.organization_id`,
    `team_product`.`product_id` AS `team_product.productId` 
    FROM `product` AS `product` 
    INNER JOIN `organization_product` AS `team_product`
        ON `product`.`id` = `team_product`.`product_id`
            AND `team_product`.`organization_id` = 'team-2' 
    ORDER BY `product`.`priority` DESC;

-- get products for team-1
SELECT `product`.`id`, `product`.`name`, `product`.`deleted`,
    `product`.`priority`, `product`.`data`,
    `product`.`created_at` AS `createdAt`,
    `team_product`.`created_by_admin` AS `team_product.created_by_admin`,
    `team_product`.`changes` AS `team_product.changes`,
    `team_product`.`expires` AS `team_product.expires`,
    `team_product`.`organization_id` AS `team_product.organization_id`,
    `team_product`.`product_id` AS `team_product.productId`
    FROM `product` AS `product`
    INNER JOIN `organization_product` AS `team_product`
        ON `product`.`id` = `team_product`.`product_id` 
            AND `team_product`.`organization_id` = 'team-1'
    ORDER BY `product`.`priority` DESC;
```

**Comment by gka** [comment]
I also just ran each of the queries on our production DB with my own user. None of the queries took more than 33ms, but because I am in 6 teams it meant that the total number of queries would be 9 (the first 3 for get user, get user products and get user teams, and then 6 more for each team)

Maybe there's a way to optimize this? Not sure if worth the effort.

**Comment by davidkokkelink** [comment]
Thanks! I think the query are okay for now. The fallback product solution is also not really needed anymore since our pricing model is so simple now

**Pull request merged**
