### PR TITLE
Add Folder.isWritableBy

### PR DESCRIPTION
**Pull request by davidkokkelink**
Adding `isWritableBy(user)` to the `Folder` method to determine whether a folder is accessible by a user (either directly or through team affiliation)

### CODE REVIEW

**Review by gka — COMMENTED** [review]
hm, I'd be surprised if this works without `await`. Also since this is a built-in ORM method we should probably also check the team invite token. If I remember correctly a user is only becoming a real member of the team once the invite token is empty (i.e. the user has accepted the invite)

**Comment by gka** [comment]
Which reminds me of our long-running task of replacing the various tokens throughout our database with `AccessToken` to make simple implementation like the one here possible in the future.

**Comment by davidkokkelink** [comment]
`return await xyz()` is the same as `return xyt()`. in fact, healthier will complain about the former because of the redundancy

**Comment by gka** [comment]
my bad. I always forget about this magic await.

**Comment by gka** [comment]
we still need to address the invite_token issue, though

**Review by gka — CHANGES_REQUESTED** [review]
we need to add a check that the user has already accepted the invitation. Otherwise this method should return `false`. The problem is that `user.hasTeam()` is a Sequelize core method that doesn't know about our `invite_token` hack.

**Comment by davidkokkelink** [comment]
Thanks, that makes sense. I added `User.hasActivatedTeam` which also checks that the `invite_token` is not set.

**Review by gka — APPROVED** [review]

**Pull request merged**
