### PR TITLE
use json column for theme.data

### PR DESCRIPTION
**Pull request by gka**
following the db migration introduced in https://github.com/datawrapper/datawrapper/pull/281 we also need to update the ORM. parsing and stringifying JSON manually becomes obsolete.

### CODE REVIEW

**Comment by gka** [comment]
test failed because the `datawrapper_orm` test db wasn't migrated yet.

**Comment by gka** [comment]
the test still failed because the change of the underlying data model revealed a bug that we had in our code: we were using `assign-deep` in the past for deep-merging theme data from extended themes. However, apparently that's not what `assign-deep` is supposed to do. Its readme says:
> This follows the same behavior as Object.assign(), and thus _does not deep clone values_.

Not sure why we didn't catch this in the past, maybe the `JSON.parse()` was somehow masking this problem. Anyhow, I switched to `merge-deep` instead of `assign-deep` to fix the data extending.

**Comment by gka** [comment]
**it's more complicated...**

so, assign-deep *does* deep assign values, but it also modifies the
references of the input objects.

to explain this, here's a first example

```js
> a = { foo: 3 }
{ foo: 3 }
> b = { foo: 9 }
{ foo: 9 }
> assign({}, a, b)
{ foo: 9 }
> a
{ foo: 3 }
> b
{ foo: 9 }
>
```

this is what I had expected. the `assign()` call copies foo=9 over
to the new object without modifying `a`.

but now let's look at a second example:

```js
> a = { foo: { bar: 3 } }
{ foo: { bar: 3 } }
> b = { foo: { bar: 9 } }
{ foo: { bar: 9 } }
> assign({}, a, b)
{ foo: { bar: 9 } }
> a
{ foo: { bar: 9 } }
> b
{ foo: { bar: 9 } }
```

as we see, in this case `assign()` had also modified the original
value of `a`.

this is what broke my test, as this caused `getAllMergedThemes`
to overwrite theme data from the last theme to all other themes.

I fixed it by combining `assign` with a deep `merge` to create
a deep copy of the data first.

**Comment by sto3psl** [comment]
I had to work with these kinds of problems before and it's worth to check out immutable data structures with [object-path-immutable](https://github.com/mariocasciaro/object-path-immutable) and it's `immutable.merge` method. With 1.2kB it's also really slim compared to Immutable.js.
Working with nested objects, it generally reduces a lot of pain points and can be worth for ORM and API.

**Comment by gka** [comment]
maybe yes. but it feels a bit too much for this PR. also we definitely would need to check how `immutable.merge` operates on arrays. `merge-deep`, for instance, merges values inside arrays as well. so `colors.palette` from an extended theme would mix with `color.palette` of the theme that extends it, which isn't what we want.

**Pull request merged**
